version: "3.9"
services:
  dev-postgres:
    image: postgres:18.1-alpine
    ports:
      - 5422:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: 
    restart: always
    networks:
      - lesson
networks:
  lesson:
